spring.application.name=progetto_finale

spring.datasource.url=jdbc:mysql://localhost:3306/progettofinale
spring.datasource.username=root
spring.datasource.password=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false

supabase.url=https://kpinbwkhlbepxxjmdeaq.storage.supabase.co
supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtwaW5id2tobGJlcHh4am1kZWFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODYwMDczODksImV4cCI6MjEwMTU4MzM4OX0.CRMrhqSsdxYbNEF6Bo7cJAh_q4yUobevBvqVDx3iClg
supabase.bucket=/storage/v1/object/progetto1/
supabase.image=/storage/v1/object/public/progetto1/

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=3a87730cc5aea2
spring.mail.password=69ce7210261074
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true